from pathlib import Path
import hashlib,json
R=Path(__file__).resolve().parents[1];E=R/'evidence/npc-lifecycle';D=R/'dist/npc-lifecycle'
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
gates=json.loads((E/'GATES.json').read_text());assert gates['npc_abcde']=='PASS'
rows=[json.loads(x) for x in (E/'client-commands.jsonl').read_text().splitlines()]
transaction=json.loads((E/'transaction.json').read_text(encoding='utf-8-sig'))
text=(R/'docs/NPC_LIFECYCLE_031.md').read_text(encoding='utf-8-sig')
text+='\n## Observed final gates\n'+json.dumps(gates,indent=2)+'\n'
text+='\n## Baseline, changed fields, artifacts\nBaseline canonical-recovery copied byte-identically; new work never republished baseline.\nChanged branch: NPC adapter facts initialize before common PREPARED persist; NPC-specific semantic load validation; interaction/checkpoint/living-state commits. No canonical/generation policy change.\n'
for label,p in [('BASELINE_JAR',E/'baseline/previous.jar'),('BASELINE_SOURCE',E/'baseline/previous-source.zip'),('MODIFIED_FILE',D/'whileaway-0.3.1-npc-lifecycle.jar'),('DIFF_FILE',E/'DIFF.patch'),('ROLLBACK.sh',E/'ROLLBACK.sh')]:text+=label+': '+str(p)+'\nSHA256='+h(p)+'\n'
text+='VERIFICATION.txt: '+str(E/'VERIFICATION.txt')+'\nSource ZIP digest is in dist/npc-lifecycle/SHA256SUMS.txt (outside archive; avoids circular self-hash).\n'
text+='\n## Commands and literal results\nWorking directory: '+str(R)+'\n'
for command,log in [('./gradlew.bat --offline runGameTestServer','baseline-tests.log'),('./gradlew.bat --offline compileJava runGameTestServer build','tests-1.log'),('pwsh -NoProfile -File tools/probe-npc-storage.ps1','probe.log'),('java @evidence/npc-lifecycle/npc-fact-run.args','npc-fact-probe.log')]:
 lines=(E/log).read_text(encoding='utf-8-sig').splitlines();text+='command: '+command+'\ninput/log: '+str(E/log)+'\n'+'\n'.join(x for x in lines if 'All ' in x and 'required tests passed' in x or 'PASS core assertions' in x or 'PASS load guard cases' in x or 'PASS NPC storage cases' in x or 'BUILD SUCCESSFUL' in x)+'\nexit: 0\n'
for item in transaction['commands']:text+=json.dumps(item,ensure_ascii=False,indent=2)+'\n'
text+='Restored JAR hash='+transaction['restored_hash']+'; modified JAR remains='+transaction['modified_hash']+'; world operations=none; archive probe is not gameplay proof.\n'
text+='\n## Actual integrated clients\nAll 11 final PIDs exited. All muted/right secondary DISPLAY1. Five independent seed copies, cut + new-process resume, same identity/generation 0, final checkpoint 4 and new work state.\n'
for row in rows:
 text+=json.dumps(row)+'\n'+(E/'client'/(row['mode']+'.txt')).read_text(encoding='utf-8')+'\n'
text+='Client launcher time sum='+str(round(sum(x['seconds'] for x in rows),3))+' seconds. Not development duration or natural survival time.\n'
text+='\n## Failure history\nDevelopment ResumeA failed with literal IllegalStateException: permanent facts lost. The harness treated npc.work=check_return_light as immutable, although completion deliberately changes current work to maintain_return_light. Production event receipts and identity were not lost. Harness now checks all non-work facts survive and separately requires exactly one expected new work state. Development Seed/CutA/ResumeA logs and old fixture profile retained; final full 11 clients rerun, not combined with development attempts.\nGit Bash in sandbox failed startup with -1073741502; original failure log retained; same copy-only JAR rollback retried in approved execution context and passed exit 0. Not a gameplay failure.\n'
text+='\nPause history: The first requested pause intended to stop after C, but D was already dispatched. D and ResumeD completed; E was blocked before client launch (PID 0, PAUSED_AT_SAFE_BOUNDARY). The original failed-dispatch row and log are preserved separately and are not counted as a real-client failure. Work resumed on 2026-09-14 at five-hour usage 2%, weekly 16%, then E was run.\n'
text+='\nAdditional environment failure: the first ResumeE attempt launched Minecraft but failed ClientTestEnvironment before openWorld with IllegalStateException: window outside requested right monitor. The verifier writes PID only after the environment checks, so PID=0 in this failed row is unrecorded, not proof that no JVM launched. No java process remained at inspection. Actual failed window bounds were not recorded; cause of displacement remains unconfirmed. Story bytes still exactly matched CutE (SHA256 5810ecef0dafdbbcffe346fbb5a2d512a938ef408534c594cbed65153daaa6e0). Log, marker and command retained in environment-resumeE-attempt1. The same untouched world was retried with the original strict monitor/audio gates; no runtime source or gate was weakened. This extra attempt is excluded from the 11 successful final processes and is reported separately.\n'
text+='\n## Model, scope and next\nCurrent primary agent performed implementation/review; no Terra/Luna delegation, no routing experiment, no per-model token measurement. Caveman HOLD/off. Automatic shutdown was revoked and remains disabled. Usage-aware safe pause was subsequently added and remains active; it pauses at a verified boundary without powering off.\nNPC A/B/C/D/E PASS is not full NPC stability. NPC death/respawn, actual unload, dimension travel, divergent copied NPC world, missing/blocked residence/light and NPC corruption actual-client cases remain NOT TESTED. Previous canonical 35 clients are historical baseline, not rerun here. Current regression: 52 previous GameTests retained within 56; 580 prior storage cases rerun; 8 NPC storage cases separate. NPC-to-NPC key persistence is tested, not NPC social simulation. Full campaign PARTIAL; composite/item/reward/fallback and natural survival not started. Next first task: real NPC exception matrix with same identity/facts/life-state assertions; no composite or art until that gate closes.\n'
(E/'VERIFICATION.txt').write_text(text,encoding='utf-8');assert (E/'VERIFICATION.txt').read_text(encoding='utf-8')==text
print('PASS NPC verification written/reopened; exact commands, 11 client records, failure history, hashes and remaining gates included')
